= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Emanuel Pilz

**Gruppe:** 12

== Was habe ich gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
* Kollaboration in einem größeren Team mit mehr als 3 Personen
* Geplante Analyse und Entwurf von Software, sowie deren zielstrebige Umsetzung
* Workflow und Zeitmanagement in Form von Scrum und Kanban
* Mit einem "Kunden" arbeiten
* Continuous Integration

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
* Alle Teammitglieder waren motiviert und engagiert, niemand ist zurückgetreten (Juhu)
* Die Leistungsstärke der Teammitglieder vor allem bei zufälliger Teamzusammenstellung war sehr schwer einschätzbar,
sodass es bei der Aufgabenverteilung teilweise Über- und Unterforderung gab.
* Sprachbarriere erschwerte teilweise die Kommunikation

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
=== Spring
Spring ist ein sehr zweischneidiges Schwert. Auf der einen Seite bot das Framework eine Menge toller Features, vor allem die Integration mit Thymeleaf und JPA.
Jedoch gab es auch öfters größere Lücken und Umstände:

* *Layouts in Thymeleaf* (insbesondere Fragments) bauen den HTML Baum von innen nach außen auf.
Die meisten Frontend Frameworks bauen die Views sinnvoll von außen nach innen auf, Thymeleaf jedoch nicht.
* *Error Validation* funktioniert zwar für Formulare gut, jedoch gibt es keine Möglichkeite
einzelne Request-Parameter zu validieren, ohne eine extra Klasse zu erstellen.

=== Salespoint
SalesPoint ist an sich eine sehr gute Library, jedoch ist die Dokumentation etwas lückenhaft.
Viele Funktionsweisen und Konzepte wurden erst durch lesen der Javadocs klar, und manches blieb bis zum Schluss unklar:

* `Currencies` beinhalten nur `EURO` und `ZERO_EURO`. (Es gibt bereits `Money#zero(CurrencyUnit)`)
* `BusinessTime` dient ja dazu, dass man zum testen nicht manuell die Uhrzeit umstellen muss, jedoch ist in der Dokumentation nicht aufgeführt
wie der Aufruf von `forward()` vorgesehen ist und diese Frage konnte auch nicht vom Tutor beantwortet werden.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
* Eigene Gruppenzusammenstellungen können gerne wieder eingeführt werden. Bitte dankeschön.
* Die Analyse- und Entwurfsdokumente des VideoShop-Prototyps sollten überarbeitet werden,
da diese im aktuellen Zustand falsche Referenzen sind.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
* Kam sehr gut mit der Gruppe aus, es gab nie Spannungen zwischen Tutor und Gruppe
* Handelt sehr verständnisvoll, freundlich und an die Gruppe angepasst
* Durchgängiges Feedback und Hinweisstellungen während des Praktikums,
sodass man meistens über seinen eigenen Entwicklungsstand in Relation zur Zeit informiert war

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
