= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.

*Von: Taeeun Kim*

*Gruppe: swt19w12*

== Was habe ich gelernt?
1. Positive Seite

Ich wollte immer wissen, wie ein Team-Projekt entwickelt werden kann und das Praktikum hat mir genau erklärt, wie es aussieht.
Am Anfang war ich mir unsicher, ob wir in kurzer Zeit alles schaffen können oder was wenn ich nichts machen kann. Aber dafür gab es die Tutoren und mein Team. Ohne Mithilfe von denen, hätte ich es nicht geschafft bzw. sehr schwer geschafft.

2. Negative Seite

Was ich von der SWT und in Inloop gelernt habe, war nicht so nützlich für das Praktikum außer UML.


== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
1. Obwohl wir 6 Personen waren, hatten wir uns alle fast immer am Di. und Do. getroffen und zusammen gearbeitet, das fande ich gut und verantwortlich.
2. Bei einem Problem hatte man sich gegenseitig geholfen.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
1. Ohne Frameworks wäre es sehr schwer bzw. braucht bestimmt mehr als die doppelte Zeit.
2. Manche Funktionen waren nicht fertig, wie z.B. MultiInventory. Das wusste ich damals nicht und dadurch habe ich etwas viel Zeit verschwendet. Aber dank der Tutorhilfe konnte ich es lösen.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
Im ersten Teil von SWT könnte man sich auch ein bisschen für das Praktikum vorbereiten lassen, wie z.B. Spring, Framework usw..

== Feedback für den Tutor
1. Die Tutorin hat uns immer die Chance zur Frage gegeben und das fand ich gut und sie war immer nett

== Sonstiges und Anmerkungen
